[package]
name = "airi-protocol"
version = "0.1.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Full implementation of the Minecraft Network Protocol Spec"
readme = "README.md"
keywords = ["minecraft","protocol","mc"]
categories = ["asynchronous","parsing"]

exclude = ["tests"]

[dependencies]
airi-macros.workspace = true
byteorder.workspace = true
serde_json.workspace = true
hex.workspace = true
rsa.workspace = true
aes.workspace = true
cfb8.workspace = true
flate2.workspace = true
thiserror.workspace = true
take_mut.workspace = true
tokio = { workspace = true, features = ["io-util"] }
async-compression = { workspace = true, features = ["tokio", "zlib"] }
