name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v7
      - run: rustup update stable && rustup default stable
      - run: rustup component add rustfmt
      - run: cargo fmt --check
  build_and_test:
    name: Build project and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - run: rustup update stable && rustup default stable
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --verbose

  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
      - uses: actions/checkout@v7
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo test --verbose

  warnings:
    runs-on: ubuntu-latest
    env:
      CARGO_BUILD_WARNINGS: deny
    steps:
      - uses: actions/checkout@v7
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features --keep-going
